"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-30

Hand-written (not autogenerated) to control table/FK ordering explicitly —
in particular the circular reference between stations and rental_contracts
(a station's active_contract_id points at a contract, a contract's
station_id points at a station), which is resolved by adding the
stations -> rental_contracts FK via ALTER TABLE after both tables exist.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "branches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )

    op.create_table(
        "extras",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("default_price", sa.Numeric(10, 2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "acriss_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("hierarchy_order", sa.Integer(), nullable=False),
        sa.Column("base_daily_rate", sa.Numeric(10, 2), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("hierarchy_order"),
    )

    op.create_table(
        "drivers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("national_id_or_passport", sa.String(length=40), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("license_number", sa.String(length=40), nullable=False),
        sa.Column("license_expiration", sa.Date(), nullable=False),
        sa.Column("id_photo_url", sa.String(length=500), nullable=True),
        sa.Column("license_photo_url", sa.String(length=500), nullable=True),
        sa.Column("documents_verified", sa.Boolean(), nullable=False),
        sa.Column("preferred_color", sa.String(length=40), nullable=True),
        sa.Column(
            "preferred_transmission",
            sa.Enum("manual", "automatic", name="transmission_type"),
            nullable=True,
        ),
        sa.Column("last_visit_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("national_id_or_passport"),
    )

    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plate", sa.String(length=12), nullable=False),
        sa.Column("make", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("acriss_category_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Available", "Rented", "InPrep", "Inactive", name="vehicle_status"),
            nullable=False,
        ),
        sa.Column("current_km", sa.Integer(), nullable=False),
        sa.Column("next_service_km", sa.Integer(), nullable=False),
        sa.Column("damage_count", sa.Integer(), nullable=False),
        sa.Column("main_photo_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["acriss_category_id"], ["acriss_categories.id"]),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plate"),
    )

    op.create_table(
        "reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("driver_first_name", sa.String(length=80), nullable=False),
        sa.Column("driver_last_name", sa.String(length=80), nullable=False),
        sa.Column("driver_email", sa.String(length=255), nullable=False),
        sa.Column("pickup_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("return_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_branch_id", sa.Uuid(), nullable=False),
        sa.Column("acriss_category_id", sa.Uuid(), nullable=False),
        sa.Column("deposit_done_online", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "cancelled", "completed", "no_show", name="reservation_status"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["pickup_branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["acriss_category_id"], ["acriss_categories.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "reservation_extras",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("extra_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["reservation_id"], ["reservations.id"]),
        sa.ForeignKeyConstraint(["extra_id"], ["extras.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id", "extra_id", name="uq_reservation_extra"),
    )

    op.create_table(
        "stations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("pairing_token", sa.String(length=255), nullable=True),
        # active_contract_id is added below, once rental_contracts exists.
        sa.Column("paired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "rental_contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("from_reservation", "walk_in", name="contract_origin"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("departure_km", sa.Integer(), nullable=True),
        sa.Column("departure_fuel_level", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum("New", "PreOpened", "Open", name="contract_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["reservation_id"], ["reservations.id"]),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"]),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"]),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"]),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # Close the circular reference: stations.active_contract_id -> rental_contracts.id.
    op.add_column("stations", sa.Column("active_contract_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_station_active_contract",
        "stations",
        "rental_contracts",
        ["active_contract_id"],
        ["id"],
    )

    op.create_table(
        "contract_extras",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("extra_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("applied_price", sa.Numeric(10, 2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["rental_contracts.id"]),
        sa.ForeignKeyConstraint(["extra_id"], ["extras.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "deposits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(10, 2), nullable=False),
        sa.Column(
            "mechanism",
            sa.Enum("online_in_advance", "in_person", name="deposit_mechanism"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "authorized", name="deposit_status"),
            nullable=False,
        ),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["rental_contracts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_id"),
    )

    op.create_table(
        "digital_signatures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("contract", "handover_report", name="signature_type"),
            nullable=False,
        ),
        sa.Column("image_base64", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["rental_contracts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "pre_handover_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("damage_diagram", sa.JSON(), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "handover_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("pre_handover_report_id", sa.Uuid(), nullable=True),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("damage_diagram", sa.JSON(), nullable=False),
        sa.Column("delivery_km", sa.Integer(), nullable=False),
        sa.Column("delivery_fuel_level", sa.String(length=20), nullable=False),
        sa.Column("signature_id", sa.Uuid(), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", name="handover_report_status"),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["rental_contracts.id"]),
        sa.ForeignKeyConstraint(["pre_handover_report_id"], ["pre_handover_reports.id"]),
        sa.ForeignKeyConstraint(["signature_id"], ["digital_signatures.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("handover_reports")
    op.drop_table("pre_handover_reports")
    op.drop_table("digital_signatures")
    op.drop_table("deposits")
    op.drop_table("contract_extras")

    op.drop_constraint("fk_station_active_contract", "stations", type_="foreignkey")
    op.drop_column("stations", "active_contract_id")

    op.drop_table("rental_contracts")
    op.drop_table("stations")
    op.drop_table("reservation_extras")
    op.drop_table("reservations")
    op.drop_table("vehicles")
    op.drop_table("drivers")
    op.drop_table("acriss_categories")
    op.drop_table("extras")
    op.drop_table("branches")

    bind = op.get_bind()
    sa.Enum(name="handover_report_status").drop(bind, checkfirst=True)
    sa.Enum(name="signature_type").drop(bind, checkfirst=True)
    sa.Enum(name="deposit_status").drop(bind, checkfirst=True)
    sa.Enum(name="deposit_mechanism").drop(bind, checkfirst=True)
    sa.Enum(name="contract_status").drop(bind, checkfirst=True)
    sa.Enum(name="contract_origin").drop(bind, checkfirst=True)
    sa.Enum(name="reservation_status").drop(bind, checkfirst=True)
    sa.Enum(name="vehicle_status").drop(bind, checkfirst=True)
    sa.Enum(name="transmission_type").drop(bind, checkfirst=True)
