// Consolidated from the per-screen STRINGS tables already authored (both
// languages) in the Claude Design project's Tablet *.dc.html files — reuse,
// not new translation work. See CLAUDE.md for why /client needs to feel
// premium and touch-first rather than administrative.
export type Lang = 'en' | 'es';

// Order per the Tablet *.dc.html designs: Rental details -> Vehicle ->
// Extras -> Documents -> Data -> Deposit -> Signature. Upselling has no
// entry of its own — it's a sub-screen inside the Vehicle step, same as
// before the reorder.
export const STEP_LABELS: Record<Lang, string[]> = {
  en: ['Rental details', 'Vehicle', 'Extras', 'Documents', 'Data', 'Deposit', 'Signature'],
  es: ['Arriendo', 'Vehículo', 'Extras', 'Documentos', 'Datos', 'Garantía', 'Firma'],
};

export const rentalDetailsStrings = {
  en: {
    title: 'Your rental details',
    noteReservation: 'From your reservation. Tap any field to change it.',
    noteWalkin: 'Entered by the executive at the counter. Please check it and correct anything.',
    chipWalkin: 'Walk-in',
    pickup: 'Pick-up',
    dropoff: 'Return',
    branch: 'Branch',
    date: 'Date',
    time: 'Time',
    groupLabel: 'Car group',
    durationLabel: 'Duration',
    days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    durationSub: 'Rate confirmed at the counter',
    back: 'Back',
    idle: 'Everything correct?',
    needsCategory: 'Choose a car group to continue.',
    needsDates: 'Return must be after pick-up.',
    confirmed: 'Details confirmed ✓',
    cta: 'Confirm details',
  },
  es: {
    title: 'Los datos de su arriendo',
    noteReservation: 'Desde su reserva. Toque cualquier campo para cambiarlo.',
    noteWalkin: 'Ingresados por el ejecutivo en el mesón. Revíselos y corrija lo que sea necesario.',
    chipWalkin: 'Sin reserva',
    pickup: 'Retiro',
    dropoff: 'Devolución',
    branch: 'Sucursal',
    date: 'Fecha',
    time: 'Hora',
    groupLabel: 'Grupo de vehículo',
    durationLabel: 'Duración',
    days: (n: number) => (n === 1 ? '1 día' : `${n} días`),
    durationSub: 'Tarifa confirmada en el mesón',
    back: 'Atrás',
    idle: '¿Está todo correcto?',
    needsCategory: 'Elija un grupo de vehículo para continuar.',
    needsDates: 'La devolución debe ser posterior al retiro.',
    confirmed: 'Datos confirmados ✓',
    cta: 'Confirmar datos',
  },
};

export const documentsStrings = {
  en: {
    idHeading: 'Identity document',
    licHeading: "Driver's licence",
    title: 'Your documents',
    titleOnFile: 'Your documents are on file',
    subtitle: 'Two documents, a photo each side. It takes about a minute.',
    subtitleOnFile: 'Nothing to scan. The agent is checking the expiry dates with you now.',
    typeId: 'ID card',
    typePassport: 'Passport',
    licNote: 'Both sides, please',
    consentPre:
      'I authorise Fleetpro to process my documents and personal data for this rental, as described in the ',
    consentPost: '.',
    policyTitle: 'Personal Data Policy',
    policyVersion: 'Version 4.2 · updated 2 Jun 2026',
    policyFoot: 'A copy is emailed with your contract.',
    close: 'Close',
    acceptContinue: 'Accept and continue',
    back: 'Back',
    continue: 'Continue',
    onFile: 'Already on file',
    captured: 'Captured and read',
    reading: 'Reading…',
    tapToScan: 'Tap to scan',
    replace: 'Replace',
    retake: 'Retake',
    looksGood: 'Looks good',
    onePhotoLeft: 'One photo left',
    photosLeft: (n: number) => `${n} photos left`,
    needPolicy: 'Please accept the data policy to continue',
    allSet: 'All set. You can continue.',
    meta: {
      pp: ['Passport photo page', 'Lay it flat, both pages visible'],
      idF: ['Front', 'Side with your photo'],
      idB: ['Back', 'Side with the barcode'],
      licF: ['Front', 'Photo and expiry date'],
      licB: ['Back', 'Classes and endorsements'],
    },
    policy: [
      [
        'What we collect',
        'Identity document images, licence images, name, document numbers and expiry dates, contact details, and the payment card used for the deposit.',
      ],
      [
        'Why we need it',
        'To verify that you are legally entitled to drive the vehicle, to issue the rental contract, and to comply with our reporting duties to traffic and tax authorities.',
      ],
      [
        'How long we keep it',
        'Document images are stored for the duration of the rental plus the legal retention period of five years.',
      ],
      [
        'Who can see it',
        'Counter staff at the branch handling your rental, our fraud-prevention team, and the authorities when the law requires it.',
      ],
      [
        'Your rights',
        'You may request access, correction, or deletion once the retention period ends by writing to privacy@fleetpro.cl.',
      ],
    ],
  },
  es: {
    idHeading: 'Documento de identidad',
    licHeading: 'Licencia de conducir',
    title: 'Sus documentos',
    titleOnFile: 'Sus documentos ya están registrados',
    subtitle: 'Dos documentos, una foto por cada lado. Toma cerca de un minuto.',
    subtitleOnFile: 'No hay nada que escanear. El ejecutivo está revisando con usted las fechas de vencimiento.',
    typeId: 'Cédula',
    typePassport: 'Pasaporte',
    licNote: 'Ambos lados, por favor',
    consentPre: 'Autorizo a Fleetpro a tratar mis documentos y datos personales para este arriendo, según lo descrito en la ',
    consentPost: '.',
    policyTitle: 'Política de Datos Personales',
    policyVersion: 'Versión 4.2 · actualizada el 2 jun 2026',
    policyFoot: 'Se envía una copia junto con su contrato.',
    close: 'Cerrar',
    acceptContinue: 'Aceptar y continuar',
    back: 'Atrás',
    continue: 'Continuar',
    onFile: 'Ya registrado',
    captured: 'Capturado y leído',
    reading: 'Leyendo…',
    tapToScan: 'Toque para escanear',
    replace: 'Reemplazar',
    retake: 'Repetir',
    looksGood: 'Se ve bien',
    onePhotoLeft: 'Queda una foto',
    photosLeft: (n: number) => `Quedan ${n} fotos`,
    needPolicy: 'Acepte la política de datos para continuar',
    allSet: 'Todo listo. Puede continuar.',
    meta: {
      pp: ['Hoja de la foto del pasaporte', 'Déjelo plano, con ambas páginas visibles'],
      idF: ['Anverso', 'El lado con su foto'],
      idB: ['Reverso', 'El lado con el código de barras'],
      licF: ['Anverso', 'Foto y fecha de vencimiento'],
      licB: ['Reverso', 'Clases y anotaciones'],
    },
    policy: [
      ['Qué recopilamos', 'Imágenes del documento de identidad y de la licencia, nombre, números de documento y fechas de vencimiento, datos de contacto y la tarjeta usada para la garantía.'],
      ['Para qué lo necesitamos', 'Para verificar que está legalmente habilitado para conducir el vehículo, emitir el contrato de arriendo y cumplir con nuestras obligaciones ante las autoridades.'],
      ['Cuánto tiempo lo guardamos', 'Las imágenes se conservan durante el arriendo más el plazo legal de cinco años.'],
      ['Quién puede verlo', 'El personal del mesón, nuestro equipo de prevención de fraude y las autoridades cuando la ley lo exige.'],
      ['Sus derechos', 'Puede solicitar acceso, corrección o eliminación una vez terminado el plazo, escribiendo a privacy@fleetpro.cl.'],
    ],
  },
};

export const dataStrings = {
  en: {
    title: 'Confirm your data',
    subtitle: "Read from your documents. Tap any field to correct it.",
    subtitleOnFile: 'Everything below is already on file. Just confirm your contact details.',
    back: 'Back',
    fFirst: 'First name',
    fLast: 'Last name',
    fNid: 'National ID / passport',
    fExpiry: 'Licence expiration',
    fEmail: 'Email',
    fPhone: 'Phone',
    badEmail: 'Enter a valid email address.',
    badPhone: 'Enter a phone number with at least 9 digits.',
    errEmail: 'The email address is not valid',
    errPhone: 'The phone number is not valid',
    hintField: 'Correct the highlighted field to continue.',
    looksRight: 'Everything looks correct?',
    confirmed: 'Data confirmed ✓',
    confirmCta: 'Confirm my data',
    phEmail: 'you@email.com',
    phPhone: '+56 9 0000 0000',
  },
  es: {
    title: 'Confirme sus datos',
    subtitle: 'Leídos de sus documentos. Toque cualquier campo para corregirlo.',
    subtitleOnFile: 'Todo lo de abajo ya está registrado. Solo confirme sus datos de contacto.',
    back: 'Atrás',
    fFirst: 'Nombres',
    fLast: 'Apellidos',
    fNid: 'RUT / pasaporte',
    fExpiry: 'Vencimiento de la licencia',
    fEmail: 'Correo electrónico',
    fPhone: 'Teléfono',
    badEmail: 'Ingrese un correo electrónico válido.',
    badPhone: 'Ingrese un teléfono con al menos 9 dígitos.',
    errEmail: 'El correo electrónico no es válido',
    errPhone: 'El número de teléfono no es válido',
    hintField: 'Corrija el campo destacado para continuar.',
    looksRight: '¿Está todo correcto?',
    confirmed: 'Datos confirmados ✓',
    confirmCta: 'Confirmar mis datos',
    phEmail: 'usted@correo.com',
    phPhone: '+56 9 0000 0000',
  },
};

export const vehicleStrings = {
  en: {
    title: 'These vehicles are available in your category',
    back: 'Back',
    continue: 'Continue',
    chosen: 'Chosen ✓',
    choose: 'Choose this one',
    youChose: (model: string, plate: string) => `You chose the ${model} · ${plate}`,
    tapToChoose: 'Tap a vehicle to choose it',
    waiting: 'Waiting for the executive to send vehicle options…',
  },
  es: {
    title: 'Estos vehículos están disponibles en su categoría',
    back: 'Atrás',
    continue: 'Continuar',
    chosen: 'Elegido ✓',
    choose: 'Elegir este',
    youChose: (model: string, plate: string) => `Eligió el ${model} · ${plate}`,
    tapToChoose: 'Toque un vehículo para elegirlo',
    waiting: 'Esperando a que el ejecutivo envíe las opciones de vehículo…',
  },
};

export const upsellStrings = {
  en: {
    yourVehicle: 'Your vehicle',
    upgradeTitle: 'Upgrade your experience',
    forJust: 'For just',
    morePerDay: 'more per day',
    keeping: 'Keeping my vehicle ✓',
    keep: 'Keep my vehicle',
    upgraded: 'Upgrade confirmed ✓',
    upgrade: 'Upgrade my vehicle',
  },
  es: {
    yourVehicle: 'Su vehículo',
    upgradeTitle: 'Mejore su experiencia',
    forJust: 'Por solo',
    morePerDay: 'más por día',
    keeping: 'Mantengo mi vehículo ✓',
    keep: 'Mantener mi vehículo',
    upgraded: 'Mejora confirmada ✓',
    upgrade: 'Mejorar mi vehículo',
  },
};

export const extrasStrings = {
  en: {
    extrasTitle: 'Add extras to your rental',
    extrasNote: 'Optional. Prices are per day.',
    perDay: ' / day',
    back: 'Back',
    continue: 'Continue',
    noExtras: 'No extras selected',
  },
  es: {
    extrasTitle: 'Agregue extras a su arriendo',
    extrasNote: 'Opcional. Los precios son por día.',
    perDay: ' / día',
    back: 'Atrás',
    continue: 'Continuar',
    noExtras: 'Sin extras seleccionados',
  },
};

export const depositStrings = {
  en: {
    depKicker: 'Security deposit',
    depTitleMain: 'Authorize the deposit on the card reader',
    depLede:
      'The amount shown on the terminal is a hold, not a charge. It is released once you return the vehicle and the contract is closed.',
    sendToReader: 'Send to the card reader',
    readerHint: 'The agent will hand you the terminal when it is ready.',
    authorizing: 'Authorizing…',
    keepCard: 'Do not remove your card.',
    depDonePrepaid: 'Already authorized ✓',
    depDoneWaived: 'Deposit waived ✓',
    depDone: 'Deposit authorized ✓',
    depSubPrepaid: 'Authorized online when you booked',
    depSubWaived: 'A Gold-tier benefit — no hold on your card',
    depSubDone: 'Hold placed on your card',
    back: 'Back',
    continue: 'Continue',
  },
  es: {
    depKicker: 'Garantía',
    depTitleMain: 'Autorice la garantía en el POS',
    depLede: 'El monto que aparece en el POS es un bloqueo, no un cobro. Se libera cuando devuelve el vehículo y se cierra el contrato.',
    sendToReader: 'Enviar al POS',
    readerHint: 'El ejecutivo le pasará el POS cuando esté listo.',
    authorizing: 'Autorizando…',
    keepCard: 'No retire su tarjeta.',
    depDonePrepaid: 'Ya autorizada ✓',
    depDoneWaived: 'Garantía exenta ✓',
    depDone: 'Garantía autorizada ✓',
    depSubPrepaid: 'Autorizada en línea al reservar',
    depSubWaived: 'Beneficio nivel Gold — sin bloqueo en su tarjeta',
    depSubDone: 'Bloqueo en su tarjeta',
    back: 'Atrás',
    continue: 'Continuar',
  },
};

export const signatureStrings = {
  en: {
    signTitle: 'Sign here with the stylus or your finger',
    signNote: 'By signing you accept the rental terms and the deposit hold.',
    padHint: 'Sign above the line',
    clear: 'Clear',
    confirm: 'Confirm Signature',
    statusIdle: 'Sign here with the stylus or your finger',
    statusInk: 'Signature captured. Confirm to close the contract.',
    kVehicle: 'Vehicle',
    kExtras: 'Extras',
    kDeposit: 'Deposit',
    doneTitle: 'Contract signed',
    contractLabel: 'Contract number',
    doneKeys: 'Please collect the keys at the counter.',
  },
  es: {
    signTitle: 'Firme aquí con el lápiz o con el dedo',
    signNote: 'Al firmar acepta las condiciones del arriendo y el bloqueo de la garantía.',
    padHint: 'Firme sobre la línea',
    clear: 'Borrar',
    confirm: 'Confirmar firma',
    statusIdle: 'Firme aquí con el lápiz o con el dedo',
    statusInk: 'Firma registrada. Confirme para cerrar el contrato.',
    kVehicle: 'Vehículo',
    kExtras: 'Extras',
    kDeposit: 'Garantía',
    doneTitle: 'Contrato firmado',
    contractLabel: 'Número de contrato',
    doneKeys: 'Retire las llaves en el mesón.',
  },
};

export const resultStrings = {
  en: {
    preReportTitle: "Here's your vehicle's condition report",
    preReportHint: 'Scan this code to view the photos and diagram before you drive off.',
    parkingLotTitle: 'All set — please proceed to the parking lot',
    parkingLotHint: 'An assistant there will complete a quick vehicle inspection with you.',
  },
  es: {
    preReportTitle: 'Aquí está el informe de estado de su vehículo',
    preReportHint: 'Escanee este código para ver las fotos y el diagrama antes de partir.',
    parkingLotTitle: 'Listo — diríjase al estacionamiento',
    parkingLotHint: 'Un asistente allí completará una breve inspección del vehículo con usted.',
  },
};
